module.exports = {
    ClientName: '',
    BankName: '',
    MoneyAmount: '',
    TchRoutineID: '',
    TchRoutineTag: '',
    Purpose: '',
    LoanDate: '',
    RepayDate: '',
    LoanAcc: '',
    RepayAcc: '',
    LoanType: '',
    InterestRate: '',
    InterestAmount: '',
}
