module.exports = {
    RemitterName: '',
    RemitterAcc: '',
    RemitterBank: '',
    PayeeName: '',
    PayeeAcc: '',
    PayeeBank: '',
    BankName: '',
    MoneyAmount: '',
    TimeMark: '',
    TransferOrient: '',
    OrgVoucherName: '',
    OrgVoucherNo: '',
    OrgVoucherAmount: '',
    TransferReason: '',
}
